version: '3.8'

services:
  patient-service:
    image: patient-service:latest
    container_name: patient-service
    ports:
      - "4000:4000"
    environment:
      - KAFKA_BROKER=kafka:9094
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/patient_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - BILLING_SERVICE_ADDRESS=billing-service
    depends_on:
      - kafka
      - postgres
    networks:
      - app-network

  # Billing Service
  billing-service:
    image: billing-service:latest
    container_name: billing-service
    ports:
      - "4001:4001"
    environment:
      - SPRING_APPLICATION_NAME=billing-service
    depends_on:
      - kafka
    networks:
      - app-network

  # API Gateway
  api-gateway:
    image: api-gateway:latest
    container_name: api-gateway
    ports:
      - "4004:4004"
    depends_on:
      - patient-service
    networks:
      - app-network

  # Analytics Service
  analytics-service:
    image: analytics-service:latest
    container_name: analytics-service
    ports:
      - "4002:4002"
    environment:
      - KAFKA_BROKER=kafka:9094
    depends_on:
      - kafka
    networks:
      - app-network

  # PostgreSQL Database
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=patient_db
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - app-network

  # Kafka
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    networks:
      - app-network

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    depends_on:
      - zookeeper
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9094
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
    ports:
      - "9094:9094"
    networks:
      - app-network
networks:
  app-network:
    driver: bridge

volumes:
  postgres-data:
    driver: local
