### POST create patient
POST http://localhost:4004/api/patients/create-patient
Accept: application/json
Content-Type: application/json

{
  "name": "Bekzhan Eldiiar uulu",
  "email": "eldiiar_b@auca.kg",
  "address": "123 main street",
  "dateOfBirth": "2003-04-12"
}

###