server:
  port: 4000
spring:
  kafka:
    properties:
      metrics.reporters: [ ]
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.ByteArraySerializer
      bootstrap-servers: ${KAFKA_BROKER:kafka:9094}

  datasource:
    url: ${SPRING_DATASOURCE_UR:jdbc:postgresql://localhost:5432/patient_db}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

billing:
  service:
    address: ${BILLING_SERVICE_ADDRESS:localhost}
    grpc:
      port: 9001

logging:
  level:
    root: info


